language: python
python:
  - '3.6'
  - 3.6-dev
  - '3.7'
  - 3.7-dev
  - '3.8'
  - 3.8-dev
install:
  - pip install -r requirements.txt
# command to run tests
script: 
  - coverage run --rcfile=.coveragerc -m unittest discover
after_success:
  - codeclimate-test-reporter --token $CODECLIMATE_REPO_TOKEN
