name: python-ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f docs/requirements.txt ]; then pip install -r docs/requirements.txt; fi
    - name: CodeClimate
      uses: paambaati/codeclimate-action@v2.2.4
      env:
        CC_TEST_REPORTER_ID: $CODECLIMATE_REPO_TOKEN
      with:
        coverageCommand: coverage run --source=uravu setup.py test
